### ISSUE TITLE
GTS Don't save in stop/restart

### ISSUE THREAD

**Issue by Heriptik** [Daniel-Forge-Development/ReforgedGTS#2]
Hello, i have a new bug with the ReforgedGTS, this don't save the Trades Listing (View Trades) and the Claims Listing (Claim Trades) if i restart my server.

Video : [https://drive.google.com/file/d/1xFM8T9Hc_jLXK_w7rBZSJxHGRnRqFnPd/view?usp=sharing](https://drive.google.com/file/d/1xFM8T9Hc_jLXK_w7rBZSJxHGRnRqFnPd/view?usp=sharing)

And the taxe still does not work.

Edit : I just saw that they are moved after reboot in the Timed out Trades when it should just stay on the list.

**Comment by danorris709** [comment]
Fixed in latest
