### ISSUE TITLE
Claim Trades

### ISSUE THREAD

**Issue by Heriptik** [Daniel-Forge-Development/ReforgedGTS#3]
Hello, these are the last two bugs that I found then I think the GTS will work perfectly

 - Tax is not applied 
 - In Claim Trades menu, the pokemon is not refresh.

Video : [https://drive.google.com/file/d/1JyNXFa87U0zrynya2l2Nfk0TAoo01QrY/view?usp=sharing](https://drive.google.com/file/d/1JyNXFa87U0zrynya2l2Nfk0TAoo01QrY/view?usp=sharing)

If I did not understand the principle of the tax, it should be applied as soon as it goes on sale to prevent players from putting anything on the GTS and not on purchase.

thanks for your jobs.

**Comment by danorris709** [comment]
Fixed in latest
